[package]
name = "task_3"
version = "0.1.0"
edition = "2021"
description = "While Statement – Task Sheet 2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
